name: contentsummariser

services:
  text1:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "7001:7000"
    environment:
      - SERVER_PORT=7000
    volumes:
      - ./server:/app
    command: npm run dev

  url1:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "7002:7000"
    environment:

      - SERVER_PORT=7000
    volumes:
      - ./server:/app
    command: npm run dev

  file1:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "7003:7000"
    environment:
      - SERVER_PORT=7000
    volumes:
      - ./server:/app
    command: npm run dev

  db1:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "7004:7000"
    environment:
      - SERVER_PORT=7000
    volumes:
      - ./server:/app
    command: npm run dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - text1
      - url1
      - file1
      - db1
