FROM node:18

WORKDIR /contentsumm/server

COPY package.json ./
COPY package-lock.json ./

RUN npm install && npm install -g nodemon
RUN npm install -g ts-node typescript

COPY . ./


EXPOSE 7000

# CMD ["node", "dist/index.js"]
CMD ["npm", "run", "dev"]
